package com.zyank.jdbc;

import java.sql.ResultSet;
import java.sql.SQLException;

import org.junit.After;
import org.junit.Assert;
import org.junit.Before;
import org.junit.BeforeClass;
import org.junit.Test;
import org.springframework.jdbc.core.JdbcTemplate;
import org.springframework.jdbc.core.RowCallbackHandler;
import org.springframework.jdbc.datasource.DriverManagerDataSource;

public class jdbcTemplateTest {

	private static JdbcTemplate jdbcTemplate;


	@BeforeClass
	public static void setUpClass() {
		String url = "jdbc:hsqldb:mem:test";
		String username = "sa";
		String password = "";
		DriverManagerDataSource dataSource = new DriverManagerDataSource(url, username, password);
		dataSource.setDriverClassName("org.hsqldb.jdbcDriver");
		jdbcTemplate = new JdbcTemplate(dataSource);
	}

	@Before
	public void setUp() {
		String createTableSql = "create memory table test" + "(id int GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY, " + "name varchar(100))";  
		   jdbcTemplate.update(createTableSql);  
	}

	@After
	public void tearDown() {
		String sql = "drop table test";
		jdbcTemplate.execute(sql);
	}

	@Test
	public void QueryTest() {
		String sql = "select * from INFORMATION_SCHEMA.SYSTEM_TABLES";

		jdbcTemplate.query(sql, new RowCallbackHandler() {
			@Override
			public void processRow(ResultSet rs) throws SQLException {
				// 2.处理结果集
				String value = rs.getString("TABLE_NAME");
				System.out.println("Column TABLENAME:" + value);
			}
		});
	}
	
	@Test
	public void insert() {
		jdbcTemplate.update("insert into test (name) values('name1')");
		jdbcTemplate.update("insert into test (name) values('name2')");
		Assert.assertEquals(2, (Object) jdbcTemplate.queryForObject("select count(*) from test", Integer.class));
	}
}
